# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca8d10a30a7bc49dd523753d5fb6fbaafe1e460e157c47ded0c436b4e805abd9d4e6b52659cd136b1866d9ed77623b1090bb67ea0847ed000a74fe2a90382139

test:
  secret_key_base: 50cee1c9ceae4213366865d9f52299c4bd84d965d071eb282601fa33ea79aefd7dd4fc770bf02b8d7348a1087da2f700b710f65b4c0630b6cb1af8cfeac50811

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
